"""
最后补完: 98 个 abbrev_dict_unanalyzed 走人工汉化字典
重点: Caltech / MIT / IIT / IISc / IIIT / EPFL / ETH / BITS / Delhi / Berlin 等
"""
import pymysql

# 人工汉化字典 (针对已经 abbrev dict 展开的英文全称)
EN_FULL_ZH = {
    'Air Force Institute of Technology': '美国空军理工学院',
    'American University in Cairo': '开罗美国大学',
    'Birla Institute of Technology and Science, Pilani': '彼拉尼理工学院',
    'Birla Institute of Technology and Science, Pilani – Goa Campus': '彼拉尼理工学院 果阿校区',
    'Bangladesh University of Professionals': '孟加拉国专业人士大学',
    'Bauhaus-Universität Weimar': '魏玛包豪斯大学',
    'Brandenburg University of Technology': '勃兰登堡工业大学',
    'Brunel University London': '布鲁内尔大学',
    'Budapest University of Technology and Economics': '布达佩斯技术与经济大学',
    'Universität der Bundeswehr München': '慕尼黑联邦国防军大学',
    'CISPA Helmholtz Center for Information Security': 'CISPA 亥姆霍兹信息安全中心',
    'California Institute of Technology': '加州理工学院',
    'Chinese Academy of Sciences': '中国科学院',
    'Chinese University of Hong Kong': '香港中文大学',
    'Chittagong University of Engineering and Technology': '吉大港工程技术大学',
    'College of William and Mary': '威廉与玛丽学院',
    'Czech Technical University in Prague': '布拉格捷克理工大学',
    'École normale supérieure Paris-Saclay': '巴黎萨克雷高等师范学院',
    'École normale supérieure de Lyon': '里昂高等师范学院',
    'École normale supérieure de Rennes': '雷恩高等师范学院',
    'Federal University of Rio Grande': '南里奥格兰德联邦大学',
    'Florida Institute of Technology': '佛罗里达理工学院',
    'Freie Universität Berlin': '柏林自由大学',
    'Higher School of Economics': '高等经济学院',
    'Hasso Plattner Institute': '哈索·普拉特纳研究院',
    'Indira Gandhi Delhi Technical University for Women': '英迪拉·甘地女子技术大学',
    'International Institute of Information Technology Bangalore': '国际信息技术学院 班加罗尔',
    'Indraprastha Institute of Information Technology Delhi': '因陀罗普罗斯塔信息技术学院 德里',
    'International Institute of Information Technology Hyderabad': '国际信息技术学院 海得拉巴',
    'Indian Institute of Science Bangalore': '印度科学理工学院 班加罗尔',
    'Indian Institute of Technology (BHU) Varanasi': '印度理工学院 瓦拉纳西',
    'Indian Institute of Technology (ISM) Dhanbad': '印度理工学院 丹巴德',
    'Indian Institute of Technology Bhilai': '印度理工学院 布莱尔',
    'Indian Institute of Technology Bhubaneswar': '印度理工学院 布巴内什瓦尔',
    'Indian Institute of Technology Bombay': '印度理工学院 孟买',
    'Indian Institute of Technology Delhi': '印度理工学院 德里',
    'Indian Institute of Technology Dharwad': '印度理工学院 达尔瓦德',
    'Indian Institute of Technology Gandhinagar': '印度理工学院 甘地讷格尔',
    'Indian Institute of Technology Guwahati': '印度理工学院 古瓦哈提',
    'Indian Institute of Technology Hyderabad': '印度理工学院 海得拉巴',
    'Indian Institute of Technology Indore': '印度理工学院 印多尔',
    'Indian Institute of Technology Jammu': '印度理工学院 查谟',
    'Indian Institute of Technology Jodhpur': '印度理工学院 焦特布尔',
    'Indian Institute of Technology Kanpur': '印度理工学院 坎普尔',
    'Indian Institute of Technology Kharagpur': '印度理工学院 卡拉格普尔',
    'Indian Institute of Technology Madras': '印度理工学院 马德拉斯',
    'Indian Institute of Technology Mandi': '印度理工学院 曼迪',
    'Indian Institute of Technology Palakkad': '印度理工学院 帕拉卡德',
    'Indian Institute of Technology Patna': '印度理工学院 巴特那',
    'Indian Institute of Technology Roorkee': '印度理工学院 鲁尔基',
    'Indian Institute of Technology Ropar': '印度理工学院 罗巴尔',
    'Indian Institute of Technology Tirupati': '印度理工学院 蒂鲁帕蒂',
    'Indian Statistical Institute, Kolkata': '印度统计学院 加尔各答',
    'Indraprastha Institute of Information Technology': '因陀罗普罗斯塔信息技术学院',
    'International Institute of Information Technology, Bhubaneswar': '国际信息技术学院 布巴内什瓦尔',
    'International Institute of Information Technology, Naya Raipur': '国际信息技术学院 新赖布尔',
    'Kempelen Institute of Intelligent Technologies': '凯姆佩林智能技术研究所',
    'Vignan\'s University': '维格南大学',
    'Visvesvaraya National Institute of Technology': '维韦斯瓦拉亚国立技术学院',
    'Visvesvaraya Technological University': '维韦斯瓦拉亚技术大学',
    'King Abdullah University of Science and Technology': '阿卜杜拉国王科技大学',
    'Indian Institute of Science Education and Research Kolkata': '印度科学教育与研究学院 加尔各答',
    'Indian Institute of Science Education and Research Pune': '印度科学教育与研究学院 浦那',
    'Indian Institute of Science Education and Research Bhopal': '印度科学教育与研究学院 博帕尔',
    'Indian Institute of Science Education and Research Mohali': '印度科学教育与研究学院 莫哈利',
    'Indian Institute of Science Education and Research Thiruvananthapuram': '印度科学教育与研究学院 特里凡得琅',
    'Università della Svizzera italiana': '瑞士意大利语区大学',
    'Università della Svizzera italiana (USI)': '瑞士意大利语区大学',
    'Universitat Politècnica de Catalunya': '加泰罗尼亚理工大学',
    'Universitat Politècnica de València': '瓦伦西亚理工大学',
    'Universidade Federal de Viçosa': '维索萨联邦大学',
    'Universidade NOVA de Lisboa': '新里斯本大学',
    'Universidade de Brasília': '巴西利亚大学',
    'Universidade de Lisboa': '里斯本大学',
    'Universidade de São Paulo': '圣保罗大学',
    'Universidade Estadual de Campinas': '坎皮纳斯州立大学',
    'Universidade Federal de Minas Gerais': '米纳斯吉拉斯联邦大学',
    'Universidade Federal de Pernambuco': '伯南布哥联邦大学',
    'Universidade Federal de Santa Catarina': '圣卡塔琳娜联邦大学',
    'Universidade Federal do Rio Grande do Sul': '南里奥格兰德联邦大学',
    'Universidade Federal Fluminense': '弗鲁米嫩塞联邦大学',
    'Universität Stuttgart': '斯图加特大学',
    'Université Paris Sciences et Lettres': '巴黎文理研究大学',
    'University of Technology of Compiègne': '贡比涅技术大学',
    'Gustave Eiffel University': '古斯塔夫·埃菲尔大学',
    'Université Paris-Nord': '巴黎北大学',
    'Université Paris-Saclay': '巴黎萨克雷大学',
    'Université Paris-Sud 11': '巴黎第十一大学',
    'Università del Piemonte Orientale': '东皮埃蒙特大学',
    'Universität des Saarlandes': '萨尔大学',
    'Saarland University': '萨尔大学',
    'Saarland Informatics Campus': '萨尔大学信息学园',
    'Sabancı University': '萨班哲大学',
    'Sorbonne University': '索邦大学',
    'Sorbonne Nouvelle University': '新索邦大学',
    'Télécom Paris': '巴黎电信学院',
    'Télécom SudParis': '南巴黎电信学院',
    'Technion – Israel Institute of Technology': '以色列理工学院',
    'Tokyo University of Science': '东京理科大学',
    'Toronto Metropolitan University': '多伦多都会大学',
    'Ulm University': '乌尔姆大学',
    'Université Paris-Est Marne-la-Vallée': '巴黎东马恩河谷大学',
    'Université Paris-Est Créteil': '巴黎东克雷泰伊大学',
    'Université Sorbonne Paris Nord': '巴黎北索邦大学',
    'University of Passau': '帕绍大学',
    'University of Salzburg': '萨尔茨堡大学',
    'Universitat Jaume I': '海梅一世大学',
    'Universitat Rovira i Virgili': '罗维拉·维尔吉利大学',
    'University of Toronto': '多伦多大学',
    'Université catholique de Louvain': '鲁汶天主教大学',
    'Université libre de Bruxelles': '布鲁塞尔自由大学',
    'Université du Québec': '魁北克大学',
    'Université du Québec à Chicoutimi': '魁北克大学 希库蒂米分校',
    'Université du Québec à Montréal': '魁北克大学 蒙特利尔分校',
    'Université du Québec en Outaouais': '魁北克大学 乌塔韦分校',
    'Université Nice Sophia Antipolis': '尼斯索菲亚·安蒂波利斯大学',
    'Université Paris-Saclay': '巴黎萨克雷大学',
    'Université Grenoble Alpes': '格勒诺布尔阿尔卑斯大学',
    'Université Paris Cité': '巴黎西岱大学',
    'Uppsala University': '乌普萨拉大学',
    'Umeå University': '于默奥大学',
    'Utrecht University': '乌得勒支大学',
    'Vienna University of Technology': '维也纳技术大学',
    'Vrije Universiteit Amsterdam': '阿姆斯特丹自由大学',
    'Wageningen University & Research': '瓦赫宁根大学及研究中心',
    'Western University': '西安大略大学',
    'École polytechnique fédérale de Lausanne': '洛桑联邦理工学院',
    'ETH Zurich': '苏黎世联邦理工学院',
    'Friedrich-Alexander-Universität Erlangen-Nürnberg': '弗里德里希·亚历山大 埃尔朗根-纽伦堡大学',
    'Friedrich Schiller University Jena': '弗里德里希·席勒 耶拿大学',
    'Goethe University Frankfurt': '歌德大学 法兰克福',
    'Hochschule für Technik und Wirtschaft des Saarlandes': '萨尔州技术与经济应用技术大学',
    'Indian Institute of Science': '印度科学理工学院',
    'Institut national de la recherche scientifique': '国家科学研究院',
    'Institut Polytechnique de Paris': '巴黎理工学院',
    'Johannes Gutenberg University Mainz': '约翰内斯·古腾堡 美因茨大学',
    'KIT': '卡尔斯鲁厄理工学院',
    'Karlsruhe Institute of Technology': '卡尔斯鲁厄理工学院',
    'Kyoto University': '京都大学',
    'KTH Royal Institute of Technology': '皇家理工学院',
    'Lancaster University': '兰卡斯特大学',
    'Laval University': '拉瓦尔大学',
    'Leibniz University Hannover': '莱布尼茨汉诺威大学',
    'Linköping University': '林雪平大学',
    'LUT University': '拉彭兰塔理工大学',
    'Ludwig Maximilian University of Munich': '慕尼黑大学',
    'Massachusetts Institute of Technology': '麻省理工学院',
    'Mines ParisTech': '巴黎矿业学院',
    'Mines Saint-Étienne': '圣艾蒂安矿业学院',
    'Mohammed VI Polytechnic University': '穆罕默德六世综合理工学院',
    'Masdar Institute of Science and Technology': '马斯达尔科学技术研究所',
    'NYU Tandon School of Engineering': '纽约大学 坦登工程学院',
    'National and Kapodistrian University of Athens': '雅典国立与卡波迪斯特里安大学',
    'National Autonomous University of Mexico': '墨西哥国立自治大学',
    'National University of Singapore': '新加坡国立大学',
    'Nanyang Technological University': '南洋理工大学',
    'Northeastern University at Qinhuangdao': '东北大学 秦皇岛分校',
    'Oregon Health & Science University': '俄勒冈健康与科学大学',
    'Polytechnique Montréal': '蒙特利尔理工学院',
    'Polytechnic University of Madrid': '马德里理工大学',
    'Polytechnic University of Milan': '米兰理工大学',
    'Polytechnic University of Turin': '都灵理工大学',
    'Polytechnic University of Bari': '巴里理工大学',
    'Polytechnic University of Valencia': '瓦伦西亚理工大学',
    'Pontifical Catholic University of Chile': '智利天主教大学',
    'Pontifical Catholic University of Rio de Janeiro': '里约热内卢天主教大学',
    'Pohang University of Science and Technology': '浦项工科大学',
    'Queen Mary University of London': '伦敦玛丽女王大学',
    'Queen\'s University': '女王大学',
    'Rensselaer Polytechnic Institute': '伦斯勒理工学院',
    'Rey Juan Carlos University': '胡安·卡洛斯国王大学',
    'RMIT University': '墨尔本皇家理工大学',
    'Royal Holloway, University of London': '伦敦大学 皇家霍洛威学院',
    'Ruhr University Bochum': '波鸿鲁尔大学',
    'RWTH Aachen University': '亚琛工业大学',
    'Sapienza University of Rome': '罗马智慧大学',
    'Scuola Normale Superiore': '比萨高等师范学校',
    'Singapore Management University': '新加坡管理大学',
    'Singapore University of Technology and Design': '新加坡科技设计大学',
    'Skolkovo Institute of Science and Technology': '斯科尔科沃科学技术研究所',
    'State University of Campinas': '坎皮纳斯州立大学',
    'Stellenbosch University': '斯泰伦博斯大学',
    'Stony Brook University': '石溪大学',
    'Technical University of Berlin': '柏林工业大学',
    'Technical University of Munich': '慕尼黑工业大学',
    'Technion – Israel Institute of Technology': '以色列理工学院',
    'Tel Aviv University': '特拉维夫大学',
    'The Open University': '开放大学',
    'Tsinghua University': '清华大学',
    'TU Dortmund': '多特蒙德工业大学',
    'TU Kaiserslautern': '凯泽斯劳滕工业大学',
    'University at Albany, SUNY': '奥尔巴尼大学',
    'University at Buffalo': '布法罗大学',
    'University of Applied Sciences': '应用技术大学',
    'University of Barcelona': '巴塞罗那大学',
    'University of Bologna': '博洛尼亚大学',
    'University of Bucharest': '布加勒斯特大学',
    'University of Buenos Aires': '布宜诺斯艾利斯大学',
    'University of Caen Normandy': '卡昂诺曼底大学',
    'University of Cape Town': '开普敦大学',
    'University of Colorado Boulder': '科罗拉多大学博尔德分校',
    'University of Colorado Colorado Springs': '科罗拉多大学科罗拉多斯普林斯分校',
    'University of Colorado Denver': '科罗拉多大学丹佛分校',
    'University of Concepción': '康塞普西翁大学',
    'University of Delaware': '特拉华大学',
    'University of Electronic Science and Technology of China': '电子科技大学',
    'University of Fukui': '福井大学',
    'University of Genoa': '热那亚大学',
    'University of Hong Kong': '香港大学',
    'University of Illinois': '伊利诺伊大学',
    'University of Illinois Chicago': '伊利诺伊大学芝加哥分校',
    'University of Illinois Springfield': '伊利诺伊大学斯普林菲尔德分校',
    'University of Illinois Urbana-Champaign': '伊利诺伊大学厄巴纳-香槟分校',
    'University of Kaiserslautern-Landau': '凯泽斯劳滕-兰道大学',
    'University of KwaZulu-Natal': '夸祖鲁-纳塔尔大学',
    'University of Lausanne': '洛桑大学',
    'University of Leeds': '利兹大学',
    'University of Liège': '列日大学',
    'University of Lille': '里尔大学',
    'University of Los Andes': '安第斯大学',
    'University of Luxembourg': '卢森堡大学',
    'University of Macau': '澳门大学',
    'University of Michigan–Dearborn': '密歇根大学 迪尔伯恩分校',
    'University of Michigan–Flint': '密歇根大学 弗林特分校',
    'University of Milano-Bicocca': '米兰比可卡大学',
    'University of Minnesota Twin Cities': '明尼苏达大学 双城分校',
    'University of Modena and Reggio Emilia': '摩德纳与雷焦艾米利亚大学',
    'University of Murcia': '穆尔西亚大学',
    'University of Münster': '明斯特大学',
    'University of Naples Federico II': '那不勒斯费德里科二世大学',
    'University of Nebraska–Lincoln': '内布拉斯加大学 林肯分校',
    'University of Nebraska Omaha': '内布拉斯加大学 奥马哈分校',
    'University of Nevada, Las Vegas': '内华达大学 拉斯维加斯分校',
    'University of Nevada, Reno': '内华达大学 雷诺分校',
    'University of Oregon': '俄勒冈大学',
    'University of Ottawa': '渥太华大学',
    'University of Padua': '帕多瓦大学',
    'University of Paris': '巴黎大学',
    'University of Paris 8': '巴黎第八大学',
    'University of Pisa': '比萨大学',
    'University of Pittsburgh': '匹兹堡大学',
    'University of Pretoria': '比勒陀利亚大学',
    'University of Rochester': '罗切斯特大学',
    'University of São Paulo': '圣保罗大学',
    'University of Science and Technology Beijing': '北京科技大学',
    'University of Science and Technology of China': '中国科学技术大学',
    'University of Santiago, Chile': '智利圣地亚哥大学',
    'University of Santiago de Compostela': '圣地亚哥-德孔波斯特拉大学',
    'University of Santiago': '圣地亚哥大学',
    'University of Seville': '塞维利亚大学',
    'University of Sheffield': '谢菲尔德大学',
    'University of South Florida': '南佛罗里达大学',
    'University of Southern Queensland': '南昆士兰大学',
    'University of Sydney': '悉尼大学',
    'University of Tampere': '坦佩雷大学',
    'University of Technology of Belfort-Montbéliard': '贝尔福-蒙贝利亚尔技术大学',
    'University of Tennessee, Knoxville': '田纳西大学 诺克斯维尔分校',
    'University of Texas at Arlington': '德克萨斯大学 阿灵顿分校',
    'University of Texas at Austin': '德克萨斯大学 奥斯汀分校',
    'University of Texas at Dallas': '德克萨斯大学 达拉斯分校',
    'University of Texas at El Paso': '德克萨斯大学 埃尔帕索分校',
    'University of Texas at San Antonio': '德克萨斯大学 圣安东尼奥分校',
    'University of Tokyo': '东京大学',
    'University of Trento': '特伦托大学',
    'University of Tübingen': '蒂宾根大学',
    'University of Tübingen': '蒂宾根大学',
    'University of Valencia': '瓦伦西亚大学',
    'University of Victoria': '维多利亚大学',
    'University of Vienna': '维也纳大学',
    'University of Warwick': '华威大学',
    'University of Western Australia': '西澳大学',
    'University of Wisconsin–Madison': '威斯康星大学 麦迪逊分校',
    'University of Wisconsin–Milwaukee': '威斯康星大学 密尔沃基分校',
    'University of Zurich': '苏黎世大学',
    'University of Évry': '埃夫里大学',
    'Vrije Universiteit Brussel': '布鲁塞尔自由大学',
    'Waseda University': '早稻田大学',
    'Warsaw University of Technology': '华沙理工大学',
    'Washington University in St. Louis': '圣路易斯华盛顿大学',
    'Weizmann Institute of Science': '魏茨曼科学研究所',
    'Western Sydney University': '西悉尼大学',
    'Würzburg University': '维尔茨堡大学',
    'Xiamen University': '厦门大学',
    'Xi\'an Jiaotong University': '西安交通大学',
    'Xi\'an Jiaotong-Liverpool University': '西交利物浦大学',
    'Yamaguchi University': '山口大学',
    'Yokohama National University': '横滨国立大学',
    'Yunnan University': '云南大学',
    'Zhejiang University': '浙江大学',
    'Zhejiang University of Technology': '浙江工业大学',
    'Tohoku University': '东北大学',
    'Amirkabir University of Technology': '阿米尔卡比尔理工大学',
    'Aristotle University of Thessaloniki': '塞萨洛尼基亚里士多德大学',
    'Autonomous University of Barcelona': '巴塞罗那自治大学',
    'Bielefeld University': '比勒费尔德大学',
    'Binghamton University': '宾厄姆顿大学',
    'Birla Institute of Technology': '彼拉尼理工学院',
    'Bremen University of Applied Sciences': '不来梅应用技术大学',
    'Carlos III University of Madrid': '马德里卡洛斯三世大学',
    'Chalmers University of Technology': '查尔姆斯理工大学',
    'Chiang Mai University': '清迈大学',
    'Dresden University of Technology': '德累斯顿工业大学',
    'Federal University of Rio Grande do Sul': '南里奥格兰德联邦大学',
    'Federal University of Rio Grande': '南里奥格兰德联邦大学',
    'Fluminense Federal University': '弗鲁米嫩塞联邦大学',
    'Ghent University': '根特大学',
    'Graz University of Technology': '格拉茨工业大学',
    'HSE University': '国家研究大学高等经济学院',
    'Hamburg University of Technology': '汉堡工业大学',
    'Hebrew University of Jerusalem': '耶路撒冷希伯来大学',
    'Indian Statistical Institute': '印度统计学院',
    'INPE': '巴西国家空间研究所',
    'Institut national de la recherche scientifique': '加拿大国家科学研究院',
    'IT University of Copenhagen': '哥本哈根信息技术大学',
    'Jaume I University': '海梅一世大学',
    'Jiangnan University': '江南大学',
    'Jilin University': '吉林大学',
    'Kanazawa University': '金泽大学',
    'Karlsruhe University of Applied Sciences': '卡尔斯鲁厄应用技术大学',
    'Kyung Hee University': '庆熙大学',
    'Lappeenranta University of Technology': '拉彭兰塔理工大学',
    'Lehigh University': '利哈伊大学',
    'Linz Institute of Technology': '林茨技术大学',
    'Lodz University of Technology': '罗兹工业大学',
    'Lomonosov Moscow State University': '莫斯科国立罗蒙诺索夫大学',
    'Manchester Metropolitan University': '曼彻斯特城市大学',
    'Manipal Academy of Higher Education': '玛尼帕尔高等教育学院',
    'Masaryk University': '马萨里克大学',
    'Maynooth University': '梅努斯大学',
    'McMaster University': '麦克马斯特大学',
    'Memorial University of Newfoundland': '纽芬兰纪念大学',
    'Middle East Technical University': '中东技术大学',
    'Moscow Institute of Physics and Technology': '莫斯科物理技术学院',
    'Nagoya University': '名古屋大学',
    'Nankai University': '南开大学',
    'National Taipei University': '国立台北大学',
    'National Tsing Hua University': '国立清华大学',
    'National Yang Ming Chiao Tung University': '国立阳明交通大学',
    'New York University': '纽约大学',
    'New York University Shanghai': '上海纽约大学',
    'New York University Abu Dhabi': '纽约大学 阿布扎比分校',
    'Northwestern Polytechnical University': '西北工业大学',
    'Norwegian University of Science and Technology': '挪威科技大学',
    'Okinawa Institute of Science and Technology': '冲绳科学技术大学院大学',
    'Osaka University': '大阪大学',
    'Otto von Guericke University Magdeburg': '奥托·冯·格里克 马格德堡大学',
    'Paris Sciences et Lettres University': '巴黎文理研究大学',
    'Paris 1 Panthéon-Sorbonne University': '巴黎第一大学 潘提翁-索邦',
    'Paris-Dauphine University': '巴黎第九大学',
    'Peking University Shenzhen': '北京大学深圳研究生院',
    'Pennsylvania State University': '宾夕法尼亚州立大学',
    'Pompeu Fabra University': '庞培法布拉大学',
    'Princess Sumaya University for Technology': '苏梅雅公主技术大学',
    'Rey Juan Carlos University': '胡安·卡洛斯国王大学',
    'Rovira i Virgili University': '罗维拉·维尔吉利大学',
    'Ruhr University Bochum': '波鸿鲁尔大学',
    'RWTH Aachen': '亚琛工业大学',
    'São Paulo State University': '圣保罗州立大学',
    'Sapienza University of Rome': '罗马智慧大学',
    'State University of Campinas': '坎皮纳斯州立大学',
    'Sungkyunkwan University': '成均馆大学',
    'Sun Yat-sen University': '中山大学',
    'Taras Shevchenko National University of Kyiv': '基辅塔拉斯·谢甫琴科国立大学',
    'Technion - Israel Institute of Technology': '以色列理工学院',
    'Technion – Israel Institute of Technology': '以色列理工学院',
    'Thapar Institute of Engineering and Technology': '塔帕尔工程与技术学院',
    'Tokyo Institute of Technology': '东京工业大学',
    'Tongji University': '同济大学',
    'Toulouse 1 Capitole University': '图卢兹第一大学',
    'Toulouse 2 Jean Jaurès University': '图卢兹第二大学  让·饶勒斯',
    'Toulouse 3 Paul Sabatier University': '图卢兹第三大学 保罗·萨巴蒂埃',
    'Toyota Technological Institute': '丰田技术研究所',
    'Tufts University': '塔夫茨大学',
    'Ulsan National Institute of Science and Technology': '蔚山科学技术院',
    'UNIST': '蔚山科学技术院',
    'Universidad Carlos III de Madrid': '马德里卡洛斯三世大学',
    'Universidad de Buenos Aires': '布宜诺斯艾利斯大学',
    'Universidad de Chile': '智利大学',
    'Universidad de Concepción': '康塞普西翁大学',
    'Universidad de los Andes': '安第斯大学',
    'Universidad de Salamanca': '萨拉曼卡大学',
    'Universidad de Santiago de Compostela': '圣地亚哥-德孔波斯特拉大学',
    'Universidad de Valparaíso': '瓦尔帕莱索大学',
    'Universidad Nacional de Colombia': '哥伦比亚国立大学',
    'Universidad Nacional de Educación a Distancia': '国立远程教育大学',
    'Universidad Politécnica de Cartagena': '卡塔赫纳理工大学',
    'Universidad Politécnica de Madrid': '马德里理工大学',
    'Universidad Politécnica de Valencia': '瓦伦西亚理工大学',
    'Universidad Rey Juan Carlos': '胡安·卡洛斯国王大学',
    'Università di Bologna': '博洛尼亚大学',
    'Università della Svizzera italiana': '瑞士意大利语区大学',
    'Universitat de Barcelona': '巴塞罗那大学',
    'Universitat de les Illes Balears': '巴利阿里群岛大学',
    'Universitat Jaume I': '海梅一世大学',
    'Universitat Politècnica de Catalunya': '加泰罗尼亚理工大学',
    'Universitat Politècnica de València': '瓦伦西亚理工大学',
    'Universitat Pompeu Fabra': '庞培法布拉大学',
    'Université Blaise Pascal': '布莱斯·帕斯卡大学',
    'Université Catholique de Louvain': '鲁汶天主教大学',
    'Université Catholique de Louvain-la-Neuve': '新鲁汶天主教大学',
    'Université de Bordeaux': '波尔多大学',
    'Université de Fribourg': '弗里堡大学',
    'Université de Genève': '日内瓦大学',
    'Université de Liège': '列日大学',
    'Université de Limoges': '利摩日大学',
    'Université de Lorraine': '洛林大学',
    'Université de Montpellier': '蒙彼利埃大学',
    'Université de Nantes': '南特大学',
    'Université de Neuchâtel': '纳沙泰尔大学',
    'Université de Pau et des Pays de l\'Adour': '波城与阿杜尔河地区大学',
    'Université de Picardie Jules Verne': '皮卡第儒勒·凡尔纳大学',
    'Université de Poitiers': '普瓦捷大学',
    'Université de Reims Champagne-Ardenne': '兰斯香槟-阿登大学',
    'Université de Rennes 1': '雷恩第一大学',
    'Université de Strasbourg': '斯特拉斯堡大学',
    'Université de Toulon': '土伦大学',
    'Université de Tours': '图尔大学',
    'Université de Valenciennes': '瓦朗谢讷大学',
    'Université d\'Évry-Val-d\'Essonne': '埃夫里-埃松河谷大学',
    'Université du Maine': '勒芒大学',
    'Université du Québec': '魁北克大学',
    'Université du Québec à Chicoutimi': '魁北克大学 希库蒂米分校',
    'Université du Québec à Montréal': '魁北克大学 蒙特利尔分校',
    'Université François Rabelais de Tours': '弗朗索瓦·拉伯雷大学 图尔',
    'Université Grenoble Alpes': '格勒诺布尔阿尔卑斯大学',
    'Université Jean Monnet': '让·莫内大学',
    'Université Libre de Bruxelles': '布鲁塞尔自由大学',
    'Université Nice Sophia Antipolis': '尼斯索菲亚·安蒂波利斯大学',
    'Université Paris 1 Panthéon-Sorbonne': '巴黎第一大学 潘提翁-索邦',
    'Université Paris 6': '巴黎第六大学',
    'Université Paris 7': '巴黎第七大学',
    'Université Paris 8': '巴黎第八大学',
    'Université Paris 13': '巴黎第十三大学',
    'Université Paris-Dauphine': '巴黎第九大学',
    'Université Paris-Descartes': '巴黎第五大学',
    'Université Paris-Diderot': '巴黎第七大学',
    'Université Pierre et Marie Curie': '皮埃尔和玛丽·居里大学',
    'Université Sorbonne Nouvelle': '新索邦大学',
    'Universiti Teknologi Malaysia': '马来西亚理工大学',
    'Universiti Kebangsaan Malaysia': '马来西亚国民大学',
    'University of Aberdeen': '阿伯丁大学',
    'University of British Columbia': '英属哥伦比亚大学',
    'University of Calcutta': '加尔各答大学',
    'University of California, Berkeley': '加州大学 伯克利分校',
    'University of California, Davis': '加州大学 戴维斯分校',
    'University of California, Irvine': '加州大学 欧文分校',
    'University of California, Los Angeles': '加州大学 洛杉矶分校',
    'University of California, Merced': '加州大学 默塞德分校',
    'University of California, Riverside': '加州大学 河滨分校',
    'University of California, San Diego': '加州大学 圣地亚哥分校',
    'University of California, San Francisco': '加州大学 旧金山分校',
    'University of California, Santa Barbara': '加州大学 圣巴巴拉分校',
    'University of California, Santa Cruz': '加州大学 圣克鲁兹分校',
    'University of Coimbra': '科英布拉大学',
    'University of Coimbra, Portugal': '葡萄牙科英布拉大学',
    'University of Delaware': '特拉华大学',
    'University of Duisburg-Essen': '杜伊斯堡-埃森大学',
    'University of Erlangen-Nuremberg': '埃尔朗根-纽伦堡大学',
    'University of Florence': '佛罗伦萨大学',
    'University of Freiburg': '弗赖堡大学',
    'University of Geneva': '日内瓦大学',
    'University of Groningen': '格罗宁根大学',
    'University of Hagen': '哈根大学',
    'University of Hamburg': '汉堡大学',
    'University of Helsinki': '赫尔辛基大学',
    'University of Hyderabad': '海得拉巴大学',
    'University of Iowa': '爱荷华大学',
    'University of Johannesburg': '约翰内斯堡大学',
    'University of Kassel': '卡塞尔大学',
    'University of Konstanz': '康斯坦茨大学',
    'University of Lausanne': '洛桑大学',
    'University of Limoges': '利摩日大学',
    'University of Lisbon': '里斯本大学',
    'University of Liverpool': '利物浦大学',
    'University of Ljubljana': '卢布尔雅那大学',
    'University of Lorraine': '洛林大学',
    'University of Manchester': '曼彻斯特大学',
    'University of Manitoba': '曼尼托巴大学',
    'University of Marburg': '马尔堡大学',
    'University of Maryland': '马里兰大学',
    'University of Michigan–Dearborn': '密歇根大学 迪尔伯恩分校',
    'University of Milan': '米兰大学',
    'University of Naples Federico II': '那不勒斯费德里科二世大学',
    'University of Nebraska–Lincoln': '内布拉斯加大学 林肯分校',
    'University of Oregon': '俄勒冈大学',
    'University of Padova': '帕多瓦大学',
    'University of Paris': '巴黎大学',
    'University of Pavia': '帕维亚大学',
    'University of Pennsylvania': '宾夕法尼亚大学',
    'University of Potsdam': '波茨坦大学',
    'University of São Paulo': '圣保罗大学',
    'University of Sannio': '桑尼奥大学',
    'University of Science and Technology of China': '中国科学技术大学',
    'University of Siegen': '锡根大学',
    'University of Southern Denmark': '南丹麦大学',
    'University of St Andrews': '圣安德鲁斯大学',
    'University of Stuttgart': '斯图加特大学',
    'University of Trier': '特里尔大学',
    'University of Tübingen': '蒂宾根大学',
    'University of Udine': '乌迪内大学',
    'University of Verona': '维罗纳大学',
    'University of Warsaw': '华沙大学',
    'University of Zurich': '苏黎世大学',
    'University of Alberta': '阿尔伯塔大学',
    'University of Freiburg': '弗赖堡大学',
    'University of Göttingen': '哥廷根大学',
    'University of Heidelberg': '海德堡大学',
    'University of Innsbruck': '因斯布鲁克大学',
    'University of Jena': '耶拿大学',
    'University of Mainz': '美因茨大学',
    'University of Münster': '明斯特大学',
    'Utsunomiya University': '宇都宫大学',
    'Vanderbilt University': '范德堡大学',
    'Vienna University of Economics and Business': '维也纳经济与管理大学',
    'Vietnam National University': '越南国家大学',
    'Virginia Tech': '弗吉尼亚理工大学',
    'Vrije Universiteit Amsterdam': '阿姆斯特丹自由大学',
    'Waseda University': '早稻田大学',
    'Weizmann Institute of Science': '魏茨曼科学研究所',
    'Wuhan University': '武汉大学',
    'Xiamen University': '厦门大学',
    'Xidian University': '西安电子科技大学',
    'Yale University': '耶鲁大学',
    'Yonsei University': '延世大学',
    'Zhejiang University': '浙江大学',
    'Zhejiang University of Technology': '浙江工业大学',
    'Swiss Federal Institute of Technology': '苏黎世联邦理工学院',
    'Swiss Federal Institute of Technology Lausanne': '洛桑联邦理工学院',
    'University of Science and Technology of China': '中国科学技术大学',
    'University of Electronic Science and Technology of China': '电子科技大学',
    'University of Chinese Academy of Sciences': '中国科学院大学',
    'Indian Institute of Technology': '印度理工学院',
}

conn = pymysql.connect(host='127.0.0.1', user='root', password='', database='csrankings', charset='utf8mb4')
cur = conn.cursor()

cur.execute("SELECT id, name_zh FROM institution WHERE name_zh_source='abbrev_dict_unanalyzed'")
hits = 0
miss = []
for iid, name_zh in cur.fetchall():
    zh = EN_FULL_ZH.get(name_zh)
    if zh:
        cur.execute("UPDATE institution SET name_zh=%s, name_zh_source='manual' WHERE id=%s", (zh, iid))
        hits += 1
    else:
        miss.append((iid, name_zh))
conn.commit()
print(f"补完: {hits} 条")
print(f"miss: {len(miss)}")
for iid, n in miss:
    print(f"  [{iid}] {n}")

cur.execute("SELECT name_zh_source, COUNT(*) FROM institution GROUP BY name_zh_source")
print("\n=== 最终分布 ===")
for s, n in cur.fetchall():
    print(f"  {s or 'NULL'}: {n}")
cur.execute("SELECT COUNT(*) FROM institution WHERE name_zh IS NULL")
print(f"剩余 NULL: {cur.fetchone()[0]}")
cur.close()
conn.close()