-- =============================================================
-- V2 · 种子数据:region + subject
-- 来源:选择 PhD 场景高频使用项
-- =============================================================

-- 顶级 region(国家/地区)
INSERT INTO region (code, name_en, name_zh) VALUES
 ('CN', 'China',         '中国'),
 ('US', 'United States', '美国'),
 ('UK', 'United Kingdom','英国'),
 ('JP', 'Japan',         '日本'),
 ('KR', 'South Korea',   '韩国'),
 ('SG', 'Singapore',     '新加坡'),
 ('HK', 'Hong Kong, China','中国香港'),
 ('TW', 'Taiwan, China', '中国台湾'),
 ('AU', 'Australia',     '澳大利亚'),
 ('CA', 'Canada',        '加拿大'),
 ('DE', 'Germany',       '德国'),
 ('FR', 'France',        '法国'),
 ('NL', 'Netherlands',   '荷兰'),
 ('CH', 'Switzerland',   '瑞士'),
 ('SE', 'Sweden',        '瑞典'),
 ('IL', 'Israel',        '以色列'),
 ('RU', 'Russia',        '俄罗斯'),
 ('BE', 'Belgium',       '比利时'),
 ('DK', 'Denmark',       '丹麦'),
 ('IT', 'Italy',         '意大利'),
 ('IE', 'Ireland',       '爱尔兰'),
 ('ES', 'Spain',         '西班牙'),
 ('NO', 'Norway',        '挪威'),
 ('FI', 'Finland',       '芬兰'),
 ('AT', 'Austria',       '奥地利'),
 ('NZ', 'New Zealand',   '新西兰'),
 ('BR', 'Brazil',        '巴西'),
 ('IN', 'India',         '印度'),
 ('SA', 'Saudi Arabia',  '沙特阿拉伯'),
 ('AE', 'UAE',           '阿联酋'),
 ('MX', 'Mexico',        '墨西哥'),
 ('ZA', 'South Africa',  '南非'),
 ('TR', 'Turkey',        '土耳其'),
 ('PL', 'Poland',        '波兰'),
 ('CZ', 'Czech Republic','捷克'),
 ('HU', 'Hungary',       '匈牙利'),
 ('GR', 'Greece',        '希腊'),
 ('PT', 'Portugal',      '葡萄牙'),
 ('EG', 'Egypt',         '埃及'),
 ('TH', 'Thailand',      '泰国'),
 ('MY', 'Malaysia',      '马来西亚'),
 ('ID', 'Indonesia',     '印度尼西亚'),
 ('PH', 'Philippines',   '菲律宾'),
 ('VN', 'Vietnam',       '越南'),
 ('AR', 'Argentina',     '阿根廷'),
 ('CL', 'Chile',         '智利'),
 ('CO', 'Colombia',      '哥伦比亚'),
 ('PE', 'Peru',          '秘鲁'),
 ('OTHER', 'Other',      '其他');

-- 学科
INSERT INTO subject (code, name_en, name_zh) VALUES
 ('ALL',      'All / Overall',                '综合'),
 ('CS',       'Computer Science',             '计算机科学'),
 ('ENG',      'Engineering',                  '工程'),
 ('MED',      'Medicine',                     '医学'),
 ('BIO',      'Life Sciences / Biology',      '生命科学 / 生物'),
 ('PHY',      'Physics',                      '物理'),
 ('CHEM',     'Chemistry',                    '化学'),
 ('MATH',     'Mathematics',                  '数学'),
 ('ECON',     'Economics',                    '经济学'),
 ('BUS',      'Business / Management',        '商科 / 管理'),
 ('LAW',      'Law',                          '法学'),
 ('SOC',      'Social Sciences',              '社会科学'),
 ('PSY',      'Psychology',                   '心理学'),
 ('ART',      'Arts & Humanities',            '人文艺术'),
 ('EDU',      'Education',                    '教育'),
 ('AGR',      'Agricultural Sciences',        '农业科学'),
 ('ENV',      'Environmental Science',        '环境科学'),
 ('MAT',      'Materials Science',            '材料科学'),
 ('STAT',     'Statistics',                   '统计');
